### ISSUE TITLE
End to end - Launch something on k8s

### ISSUE THREAD

**Issue by oponder** [giantswarm/happa#4]
Hook up Happa to k8s api somehow and actually launch something based on the docker compose that the user gave.

Limiting scope to just a very simple compose file like this:

```
helloworld:
  image: index.docker.io/giantswarm/helloworld
  ports:
    - "8080:8080"
```

This should give us a good idea of all the places where we have to fill in more code.
